[project]
name = "context"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=3.4.3",
    "dataclasses>=0.8",
    "dotenv>=0.9.9",
    "openai-agents>=0.2.0",
]
